/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package montecarlomethod;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aels21
 */
public class Salida2 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Salida2() {
      initComponents();
      setLocationRelativeTo(null);
      
      String[] headerTablaSolucion2 = {"Nro","Dia","Camion del Dia","Rn","Kilogramos","Rn","Tipo de carga","Duracion","Costo de descarga"};
      DefaultTableModel modelTablaSolucion2 = new DefaultTableModel(null, headerTablaSolucion2);
        
        
      for (int i = 0; i < SeudoRandomMethod.cantidadDeCamionesStatic; i++) {
          String[] fila = new String[9];
          fila[0] = String.valueOf(i + 1);
          fila[1] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][0] + 1);
          fila[2] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][1] + 1);
          fila[3] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][2]);
          fila[4] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][3]);
          fila[5] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][4]);
          int tipoCarga = (int)SeudoRandomMethod.tablaSolucion2Static[i][5];
          fila[6] = tipoCarga == 1 ? "A" :(tipoCarga == 2 ? "B" : "C");
          fila[7] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][6]);
          fila[8] = String.valueOf(SeudoRandomMethod.tablaSolucion2Static[i][7]);
          
          modelTablaSolucion2.addRow(fila);
      }
        

      JtablaSolucion2.setModel(modelTablaSolucion2);
      
      System.out.println("Cantidad carga A: ");
      System.out.println(SeudoRandomMethod.cantCargaA);
      System.out.println("Cantidad carga B: ");
      System.out.println(SeudoRandomMethod.cantCargaB);
      System.out.println("Cantidad carga C: ");
      System.out.println(SeudoRandomMethod.cantCargaC);
      System.out.println(SeudoRandomMethod.totalPagarStatic); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtablaSolucion2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The MonteCarlo Project");
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MainPanel.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JtablaSolucion2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtablaSolucion2);

        MainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 730, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salida2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salida2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtablaSolucion2;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
